# Generated by Django 5.2.4 on 2025-07-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_student_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
    ]
